/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.home;

import com.databaseCon.DB;
import com.login.MemberRepository;
import java.math.BigDecimal;
import javax.swing.JFrame;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author David Pude
 */
public final class HomeFrame extends javax.swing.JFrame {

    private String userId;

    public HomeFrame() {
    }
    
    /**
     * Creates new form HomeFrame
     * @param id
     */
    public HomeFrame(String id) {
        initComponents();
        displayReservationRows();
        displayPricingRows();
        
        userId = id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reservations = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        area = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        reserve = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        participantsCount = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        pricing = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        year = new javax.swing.JComboBox<>();
        date = new javax.swing.JComboBox<>();
        month = new javax.swing.JComboBox<>();
        time = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("E-GYM");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("E-GYM");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 100));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reservations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Reserve for", "Date and Time", "Area", "Number of participants"
            }
        ));
        reservations.setEnabled(false);
        jScrollPane1.setViewportView(reservations);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 650, 930));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Reservations");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 710, 980));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Date and Time:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel6.setText("Area:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));
        jPanel4.add(area, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 270, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setText("Pricing:");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        reserve.setText("Submit");
        reserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveActionPerformed(evt);
            }
        });
        jPanel4.add(reserve, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel8.setText("Number of participants:");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        participantsCount.setText("0");
        participantsCount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                participantsCountKeyReleased(evt);
            }
        });
        jPanel4.add(participantsCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 270, 30));

        jLabel9.setText("Price:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        price.setEnabled(false);
        jPanel4.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 270, 30));

        pricing.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Area", "Number of Participants", "Price"
            }
        ));
        jScrollPane2.setViewportView(pricing);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 337, 620, 400));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel10.setText("Reserve now:");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2023", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991" }));
        jPanel4.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        date.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel4.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jPanel4.add(month, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeActionPerformed(evt);
            }
        });
        jPanel4.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 60, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, 1210, 980));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void reserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveActionPerformed
        MemberRepository memberRepo = new MemberRepository();
        
        int id = Integer.parseInt(this.userId);
        
        String dtime = (String)year.getSelectedItem()
                  + "-" + (String)month.getSelectedItem()
                  + "-" + (String)date.getSelectedItem() 
                  + " " + time.getText();
        String spot = area.getText();
        int count = Integer.parseInt(participantsCount.getText());
        ReservationEntity reservationEntity = new ReservationEntity(
                id, 
                dtime, 
                spot, 
                count
        );
        
        ReservationRepository reservationRepo = new ReservationRepository();
        
        int reservationId = reservationRepo.saveReservation(reservationEntity);
        
        String fullname = memberRepo.getMemberInfo(userId);
        
        if (reservationId != 0) {
            DefaultTableModel model = (DefaultTableModel) reservations.getModel();
            model.addRow(new Object[]{reservationId,fullname,dtime,spot,count});
        }
    }//GEN-LAST:event_reserveActionPerformed

    private void participantsCountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_participantsCountKeyReleased
        BigDecimal p = BigDecimal.ZERO;
        
        if (area.getText().equals("court")) {
            if (!participantsCount.getText().equals("")
                    && Integer.parseInt(participantsCount.getText()) <= 5) {
                p = BigDecimal.valueOf(100.00);
            }
        }
        
        price.setText(p.toString());
    }//GEN-LAST:event_participantsCountKeyReleased

    private void timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            HomeFrame frame = new HomeFrame();
            
            frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
            frame.setUndecorated(true);
            frame.setVisible(true);
        });
    }
    
    public void displayReservationRows() {
        try {
            String query = "select * from reservation";
            Statement st = DB.con.prepareStatement(query);

            ResultSet rs = st.executeQuery(query);

            DefaultTableModel model = (DefaultTableModel) reservations.getModel();

            String id, reservationFor, reservationDate, a, participants;
            while(rs.next()) {
                MemberRepository memberRepo = new MemberRepository();
                
                id = rs.getString(1);
                reservationFor = memberRepo.getMemberInfo(rs.getString(2));
                reservationDate = rs.getString(3);
                a = rs.getString(4);
                participants = rs.getString(5);

                model.addRow(new Object[]{id, reservationFor, reservationDate, a, participants});
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    public void displayPricingRows() {
        try {
            String query = "select * from area";
            Statement st = DB.con.prepareStatement(query);

            ResultSet rs = st.executeQuery(query);

            DefaultTableModel model = (DefaultTableModel) pricing.getModel();

            String name, count, p;
            while(rs.next()) {
                name = rs.getString(2);
                count = rs.getString(3);
                p = rs.getString(4);

                model.addRow(new Object[]{name, count, p});
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField area;
    private javax.swing.JComboBox<String> date;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JTextField participantsCount;
    private javax.swing.JTextField price;
    private javax.swing.JTable pricing;
    private javax.swing.JTable reservations;
    private javax.swing.JButton reserve;
    private javax.swing.JTextField time;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
